version: "3"
services:
  weather-app:
    build: .
    ports:
      - 2112:2112
    environment:
      - WEATHER_APP_ID=TBD

  prometheus:
    image: prom/prometheus:v2.0.0
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:8.3.3
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password