# my global config
global:
  scrape_interval:     50s # Set the scrape interval to every 50s seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'weather-app'
    scrape_interval: 50s
    static_configs:
      - targets:
        - weather-app:2112