{
 "title": "WeatherAPP_Scrapper",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Evolution of temperature of the 2 hottest cities polled",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "topk(2,current_temperature)", "legendFormat": "{{city}}" }
   ]
  },
  {
   "title": "Rain precipitation in Paris",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mm/h" } },
   "targets": [
    {
     "expr": "current_precipitation{city=\"paris\"}",
     "legendFormat": "{{city}}"
    }
   ]
  },
  {
   "title": "Forecasted Temperature vs Current Temperature in Paris (3h forecast)",
   "type": "timeseries",
   "description": "We expose 3h forecasted data with prometheus. We, then, use a 3h offset",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "forecast_temperature{city=\"paris\"} offset 3h",
     "legendFormat": "forecasted Temperature"
    },
    {
     "expr": "current_temperature{city=\"paris\"}",
     "legendFormat": "Current Temperature"
    }
   ]
  },
  {
   "title": "Temperature over time with a threshold",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "current_temperature", "legendFormat": "{{city}}" }
   ]
  }
 ]
}